server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: on
          enabled: true
  application:
    name: proxy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


