localstorage:
  path: localstorage


aws:
  config:
    endpoint: "http://localhost:4566"
    region: us-west-1
    secretKey: stub
    accessKey: stub
  s3:
    bucket:
      file: file-bucket

  sqs:
    queue:
      file: file-queue


server:
  port: 8087

spring:
  application:
    name: file-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


